name: Playwright Tests

on:
  schedule:
    - cron: '0 20 * * *'
  push:
    branches: [ main, practice-3]
  pull_request:
    branches: [ main, practice-3]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Run Playwright tests
        run: npx playwright test --reporter=html

      - name: Upload HTML Report
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report
